package corba.SmartHome;


/**
* SmartHome/TempsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Temps.idl
* samedi 6 d�cembre 2025 14 h 30 CET
*/

public interface TempsOperations 
{
  int getHeure ();
  int getJour ();
  int getWeekend ();
} // interface TempsOperations
