package corba.SmartHome;


/**
* SmartHome/TempsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Temps.idl
* samedi 6 d�cembre 2025 14 h 30 CET
*/

public abstract class TempsPOA extends org.omg.PortableServer.Servant
 implements TempsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getHeure", new Integer (0));
    _methods.put ("getJour", new Integer (1));
    _methods.put ("getWeekend", new Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SmartHome/Temps/getHeure
       {
         int $result = (int)0;
         $result = this.getHeure ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // SmartHome/Temps/getJour
       {
         int $result = (int)0;
         $result = this.getJour ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // SmartHome/Temps/getWeekend
       {
         int $result = (int)0;
         $result = this.getWeekend ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SmartHome/Temps:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Temps _this() 
  {
    return TempsHelper.narrow(
    super._this_object());
  }

  public Temps _this(org.omg.CORBA.ORB orb) 
  {
    return TempsHelper.narrow(
    super._this_object(orb));
  }


} // class TempsPOA
