package corba.SmartHome;


/**
* SmartHome/Temps.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Temps.idl
* samedi 6 d�cembre 2025 14 h 30 CET
*/

public interface Temps extends TempsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Temps
