package corba.SmartHome;

/**
* SmartHome/TempsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Temps.idl
* samedi 6 d�cembre 2025 14 h 30 CET
*/

public final class TempsHolder implements org.omg.CORBA.portable.Streamable
{
  public Temps value = null;

  public TempsHolder ()
  {
  }

  public TempsHolder (Temps initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TempsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TempsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TempsHelper.type ();
  }

}
